const app=document.querySelector('#app');
const state={rounds:[],round:0,score:0,guesses:[],startedAt:0,player:'Player',marker:null,map:null};
const haversine=(a,b)=>{const R=3958.8,rad=x=>x*Math.PI/180,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(q));};
const points=miles=>Math.max(0,Math.round(5000*Math.exp(-miles/1200)));
const fmt=n=>Math.round(n).toLocaleString();
async function init(){state.rounds=await(await fetch('/rounds.json')).json();home();}
function home(){app.innerHTML=`<div class="shell"><section class="hero"><div class="pill" style="display:inline-block">18 travel-photo rounds</div><h1>🌎 Around the World with Floyd</h1><p class="subtitle">Study the photo, drop a pin, and earn up to 5,000 points based on distance.</p><div class="card" style="max-width:520px;margin:28px auto;text-align:left"><label><strong>Player name</strong><input id="name" maxlength="24" placeholder="Enter your name"></label><div class="row center" style="margin-top:16px"><button class="btn" id="start">Start game</button></div></div></section></div>`;document.querySelector('#start').addEventListener('click',()=>{state.player=document.querySelector('#name').value.trim()||'Player';state.startedAt=Date.now();showRound();});}
function showRound(){const r=state.rounds[state.round];app.innerHTML=`<div class="shell"><div class="row spread"><span class="pill">Round ${state.round+1} of ${state.rounds.length}</span><span class="pill">${fmt(state.score)} points</span></div><h2>Where was this photo taken?</h2><div class="grid"><div class="card"><img class="photo" src="/photos/round-${String(state.round+1).padStart(2,'0')}.jpg" alt="Floyd travel photo"></div><div class="card"><p class="muted">Tap the map to place or move your guess.</p><div id="map"></div><div class="row center" style="margin-top:14px"><button class="btn" id="submit" disabled>Submit guess</button></div></div></div></div>`;state.marker=null;state.map=L.map('map',{worldCopyJump:true,minZoom:1}).setView([20,0],1);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(state.map);state.map.on('click',e=>{if(state.marker)state.marker.setLatLng(e.latlng);else state.marker=L.marker(e.latlng).addTo(state.map);document.querySelector('#submit').disabled=false;});document.querySelector('#submit').addEventListener('click',()=>reveal(r));}
function reveal(r){const g=state.marker.getLatLng(),miles=haversine(g,r),earned=points(miles);state.score+=earned;state.guesses.push({round:state.round,name:r.name,miles,earned,category:r.category,seconds:(Date.now()-state.startedAt)/1000});app.innerHTML=`<div class="shell"><div class="card"><div class="pill" style="display:inline-block">Round ${state.round+1} result</div><h2>${r.name}</h2><div class="row"><div><div class="big">${fmt(earned)}</div><div class="muted">points</div></div><div><div class="big">${miles<1?miles.toFixed(1):fmt(miles)}</div><div class="muted">miles away</div></div></div><div id="map" style="margin-top:16px"></div><div class="row center" style="margin-top:16px"><button class="btn" id="next">${state.round===state.rounds.length-1?'See final awards':'Next round'}</button></div></div></div>`;const m=L.map('map').setView([(g.lat+r.lat)/2,(g.lng+r.lng)/2],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(m);L.marker(g).addTo(m).bindPopup('Your guess');L.marker([r.lat,r.lng]).addTo(m).bindPopup(r.name).openPopup();const line=L.polyline([[g.lat,g.lng],[r.lat,r.lng]],{weight:4}).addTo(m);m.fitBounds(line.getBounds().pad(.35));document.querySelector('#next').addEventListener('click',()=>{state.round++;state.startedAt=Date.now();state.round<state.rounds.length?showRound():finale();});}
function finale(){const gs=state.guesses,best=[...gs].sort((a,b)=>a.miles-b.miles)[0],worst=[...gs].sort((a,b)=>b.miles-a.miles)[0],avg=gs.reduce((s,x)=>s+x.miles,0)/gs.length,usa=gs.filter(x=>x.category==='USA').reduce((s,x)=>s+x.earned,0),intl=gs.filter(x=>x.category==='International').reduce((s,x)=>s+x.earned,0),half=Math.floor(gs.length/2),first=gs.slice(0,half).reduce((s,x)=>s+x.earned,0)/half,second=gs.slice(half).reduce((s,x)=>s+x.earned,0)/(gs.length-half);const awards=[['🏆 World Traveler',`${state.player} — ${fmt(state.score)} total points`],['🎯 Bullseye Award',`${best.name} — ${best.miles.toFixed(1)} miles away`],['🌍 Geography Teacher',`${fmt(avg)}-mile average accuracy`],['🧭 Explorer Award',second>first?`Improved by ${fmt(second-first)} points per round`:'Strongest performance came early'],['😂 Lost at Sea Award',`${worst.name} — ${fmt(worst.miles)} miles away`],['🚀 Speed Demon',`${(gs.reduce((s,x)=>s+x.seconds,0)/gs.length).toFixed(1)} seconds per guess`],['🇺🇸 USA Expert',`${fmt(usa)} points on U.S. locations`],['🌎 International Explorer',`${fmt(intl)} points overseas`]];app.innerHTML=`<div class="shell"><div class="hero"><h1>🏆 Final Results</h1><p class="subtitle">${state.player}, you scored <strong>${fmt(state.score)}</strong> out of ${fmt(state.rounds.length*5000)} possible points.</p></div><div class="card"><h2>Extra awards</h2>${awards.map(a=>`<div class="award"><strong>${a[0]}</strong><div class="muted">${a[1]}</div></div>`).join('')}<div class="row center" style="margin-top:18px"><button class="btn" id="again">Play again</button></div></div></div>`;document.querySelector('#again').addEventListener('click',()=>{Object.assign(state,{round:0,score:0,guesses:[],marker:null,map:null});home();});}
init();
